services:
  - type: web
    name: cinefio-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health.php
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_ENV
        value: production
