<div class="px-4 py-5 d-flex flex-column min-vh-100 justify-content-center text-center">
    <i class="bi bi-exclamation-triangle fs-1 text-warning mb-3"></i>
    <h3 class="text-white fw-bold">404 - Página Não Encontrada</h3>
    <p class="text-gray small text-center px-4">Desculpe, a página solicitada não pôde ser encontrada.</p>
    <div class="mt-4">
        <a href="/dashboard" class="btn btn-accent refract-btn-purple rounded-pill px-4 py-2 small fw-bold">Voltar ao Início</a>
    </div>
</div>
